### PR TITLE
Made sure the extension isn't in the original name

### PR DESCRIPTION
**Pull request by bdunogier**
Ideally, the watchlist shouldn't care. I'm sure it's part of a TODO. But this will at least make it work in the meantime :-)

### CODE REVIEW

**Comment by bdunogier** [comment]
Ping @lolautruche ;)

**Comment by lolautruche** [comment]
+1

**Comment by bdunogier** [comment]
Damnit

> Pull Requests that have a failing status can’t be merged from a phone.

**Comment by lolautruche** [comment]
lol
I'm pretty sure you can use the desktop version :-)

**Comment by bdunogier** [comment]
Right :p

**Pull request merged**
